# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercd',
            name='id',
        ),
        migrations.AlterField(
            model_name='usercd',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.User'),
        ),
    ]
