# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20161227_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercd',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
