# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20161227_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='usercd',
            name='city',
        ),
        migrations.RemoveField(
            model_name='usercd',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='usercd',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Address'),
        ),
    ]
