# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20170114_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamowienie',
            name='status',
        ),
        migrations.RemoveField(
            model_name='zamowienie',
            name='statustime',
        ),
    ]
