# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20170114_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='status',
            field=models.IntegerField(default=None, verbose_name='Obecny status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='statustime',
            field=models.DateTimeField(default=None, verbose_name='Czas zmiany'),
        ),
    ]
