# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20170114_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zamowienie',
            options={'get_latest_by': 'statustime'},
        ),
    ]
