# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0008_koszyk_zamowienie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obraz', models.ImageField(max_length=4096, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Producent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, unique=True)),
                ('opis', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='ToSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iloscSztuk', models.IntegerField()),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Produkt')),
                ('zamowienie', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.Zamowienie')),
            ],
        ),
        migrations.AddField(
            model_name='galeria',
            name='produkt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Produkt'),
        ),
    ]
