# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='producent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Producent'),
            preserve_default=False,
        ),
    ]
