# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_produkt_producent'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='iloscSztuk',
            field=models.IntegerField(default=0, max_length=2000),
        ),
    ]
