# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_produkt_iloscsztuk'),
    ]

    operations = [
        migrations.CreateModel(
            name='KartaGraficzna',
            fields=[
                ('produkt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.Produkt')),
                ('wyjscia', models.CharField(max_length=255)),
                ('zlacze', models.CharField(max_length=255)),
                ('TDP', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlytaGlowna',
            fields=[
                ('produkt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.Produkt')),
                ('sockety', models.CharField(max_length=255)),
                ('wyjscia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Procesor',
            fields=[
                ('produkt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.Produkt')),
                ('socket', models.CharField(max_length=255)),
                ('TDP', models.CharField(max_length=255)),
            ],
        ),
    ]
