# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_produkt_cena'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='iloscSztuk',
            field=models.IntegerField(default=0),
        ),
    ]
