# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20170116_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liczba', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='produkt',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Kategoria'),
        ),
    ]
